### ISSUE TITLE
While using "by.react" method, system is throwing the error "Failed: javascript error: Cannot read property 'resq$$' of undefined"

### ISSUE THREAD

**Issue by bharadwaj92-qa** [abhinaba1080/protractor-react-selector#7] opened 2020-05-22 07:56 UTC
1.I have first installed the plugin "Protractor-React-Selector", mentioned it in Conf.js file as :
plugins: [
    {
      package: 'protractor-react-selector'  
    }
  ]
2. Added extension 'React Developer tools' ext in Chrome browser and did f12 and using 'Components' tab, i have identified component name and props details for one of my web element.
3, I have used the code in this way in my testcase.js:
const button=element(by.react('t',{content:  "Bharadwaj Nandiraju"}));
button.click();

Result: Ran Protractor conf.js
Browser launched and opened my ReactJS application.
Browser closed, test case got failed and system has thrown the message as:
"Failed: javascript error: Cannot read property 'resq$$' of undefined"

Installed:
resq": "^1.7.1",
"protractor-react-selector": "^2.2.2",

I AM NOT SURE IF I HAVE MISSED ANYTHING ELSE PART OF CONFIGURATION OR INSTALLATION

**Comment by abhinaba-ghosh** [comment] 2020-05-22 09:18
Hi, The Issue is fixed in recent version V2.2.3.

Make sure you run ```await browser.waitForReact()``` before identifying react elements.

**Comment by bharadwaj92-qa** [comment] 2020-05-22 11:02
> Hi, The Issue is fixed in recent version V2.2.3.
> 
> Make sure you run `await browser.waitForReact()` before identifying react elements.

Hi, Yes now it is working and I am not facing any error.
Thanks for your solution and your time.

**Closed as completed** 2020-05-22 11:02 UTC
