### ISSUE TITLE
How can i make it work?

### ISSUE THREAD

**Issue by kripors** [abhinaba1080/protractor-react-selector#6] opened 2020-05-15 15:07 UTC
I have installed protractor-react-selector , but i can't make it work , i received the following error:

1) Login  Login
  - Failed: browser.waitForReact is not a function
  
![Captura de Tela 2020-05-15 às 12 06 02](https://user-images.githubusercontent.com/58744321/82065508-93ff3380-96a4-11ea-90ae-9348a553aab4.png)

can you help me?

**Comment by abhinaba-ghosh** [comment] 2020-05-15 20:55
Hi @kripors , I am glad that you asked this question.
First thing, I am assuming that you are using the latest version of the protractor-react-selector (v2.2.3). If not, I suggest you jump to the recent version as quickly as possible. 

Protractor-react-selector needs to wait for the react root to be loaded in your application. For that, you need to find out what is the react root for your application. 

just an example:

if the react app's entry point is:

```js
// imports

const App = () => (
  <div id='root'>
    <MyComponent />
    <MyComponent someBooleanProp={true} />
  </div>
)
```
Then the root of react app is ```#root```

in that case, you need to wait for this react app to be loaded in a ```beforeAll```/```before``` hook or in ```onPrepare``` hook in protractor configuration.

So, 
- if your react app root is set to ```#root``` (css-selector), then you have to go like this:
```js
 beforeAll(async function () {
    await browser.waitForReact()
  })
```
- if root is set to something else except ```#root```, then you need to pass the information in the ```waitForReact()``` function. if you have the entry point of your react app is:
```js
const App = () => (
  <div id='mount'>
    <MyComponent />
    <MyComponent someBooleanProp={true} />
  </div>
)
```
then your ```beforeAll`` hook should look like:
```js
 beforeAll(async function () {
    await browser.waitForReact(10000, '#mount') // I have set a timeout of 10000, you can set anything
  })
```

If this part is completed, then you can use ```by.react``` anywhere in the project. For some sample tests, visit [here](https://github.com/abhinaba-ghosh/protractor-react-selector/blob/master/test/spec.js)

Let me know, if this helps!

**Comment by bud-mo** [comment] 2020-05-29 09:57
I have the same issue.
Following the steps You described I still get the error:
```
Failed: browser.waitForReact is not a function
TypeError: browser.waitForReact is not a function
    at UserContext.<anonymous> (/home/bud/myproject/e2e/specs/login_spec.js:18:17)
    at /home/bud/myproject/node_modules/jasminewd2/index.js:112:25
    at new ManagedPromise (/home/bud/myproject/node_modules/selenium-webdriver/lib/promise.js:1077:7)
    at ControlFlow.promise (/home/bud/myproject/node_modules/selenium-webdriver/lib/promise.js:2505:12)
    at schedulerExecute (/home/bud/myproject/node_modules/jasminewd2/index.js:95:18)
    at TaskQueue.execute_ (/home/bud/myproject/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/home/bud/myproject/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/home/bud/myproject/node_modules/selenium-webdriver/lib/promise.js:2974:25)
    at /home/bud/myproject/node_modules/selenium-webdriver/lib/promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: Run beforeAll in control flow
    at UserContext.<anonymous> (/home/bud/myproject/node_modules/jasminewd2/index.js:94:19)
    at attempt (/home/bud/myproject/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
    at QueueRunner.run (/home/bud/myproject/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
    at QueueRunner.execute (/home/bud/myproject/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4199:10)
    at queueRunnerFactory (/home/bud/myproject/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:909:35)
    at UserContext.fn (/home/bud/myproject/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:5325:13)
    at attempt (/home/bud/myproject/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
    at QueueRunner.run (/home/bud/myproject/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
    at QueueRunner.execute (/home/bud/myproject/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4199:10)
    at queueRunnerFactory (/home/bud/myproject/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:909:35)
From asynchronous test: 
Error
    at Suite.<anonymous> (/home/bud/myproject/e2e/specs/login_spec.js:17:2)
    at addSpecsToSuite (/home/bud/myproject/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1107:25)
    at Env.describe (/home/bud/myproject/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1074:7)
    at describe (/home/bud/myproject/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4399:18)
    at Object.<anonymous> (/home/bud/myproject/e2e/specs/login_spec.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```
I have added the plugin and this is an example of a test I am doing (moving to `beforeAll` or `onPrepare` does not change the result)

```javascript
	it('User performs a login', async function() {
		await browser.waitForAngularEnabled(false);
		await browser.get('http://localhost:8080/');
		await browser.waitForReact(10000, '#app');
		await browser.wait(until.presenceOf(element(by.react('MyView')), 5000, 'Element taking too long to appear in the DOM'));
		expect(element(by.react('MyView')).isPresent()).toBeTruthy();
	});
```

**Comment by abhinaba-ghosh** [comment] 2020-05-29 10:23
hi @bud-mo , looks wired! Can you share a sample repo, so that I can reproduce the same in my machine?

And make sure you have ```protractor-react-selector``` as a plugin in your protractor configuration file with the following code:

```js
exports.config = {
  // ... the rest of your config
  plugins: [
    {
      package: 'protractor-react-selector'
    }
  ]
}
```

**Comment by bud-mo** [comment] 2020-05-29 13:05
Hi @abhinaba-ghosh , yes the plugins is defined correctly.
Creating a new repo the issue can't be reproduced so I compared the whole `package.json` and find out I was using protractor at version `5.4.4`. Updating protractor to `7.0.0` the error disappear and some tests are working great (other don't but maybe is another issue).
@kripors which version of protractor are You using?

**Comment by abhinaba-ghosh** [comment] 2020-05-29 13:21
@bud-mo That is great news. but, I have used protractor 5.3.1 version for all the sample tests and it worked fine. So, there is something fishy with the 5.4.x version. I will test more and find out the root cause. 

Let me know your analysis of the other test cases. If you find any bug in the library, please raise a ticket.

**Closed as completed** 2020-06-04 07:52 UTC
Labels: good first issue, awaiting feedback
